---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel.json: AgApmo0aHBnmVhfuEOPQmboj0EyetQeSrqCavmtWoEI5AqHGi0XPWiqVSlRgb9cNTMCNGiov79Yqy1p2eneuIuc18aUodUMqA7KYbHVW10BslqYFrMmPGqfmghtPS2UYMrGSmKShrM8yMfLL3znREO4Ql8svBOM+DgOi9Kq07fMJovIdtqiWDBQVvxrsQkYxEVv3vj3r2NNZab2s/cmxPl/MAgud9Oo8DXCrP8/5McWc8siMLxpIkytYua+pDva5iVaeeQw9Qnq6t9eto0/jmwN3dLJOol2XN+yx79FEEdOuLQ2eXbIbv7arLFNz67A/0FJgWhLH1ztB1zPKqayb4ZSBjSmN9B9agMbj1hwuwoLYA/8ypul7J5vM7pxxb+DSut82H/FTSSR3FX6i6sgQktaDCdID44A/Houz+GHKDBsczN7EPFq+y9nwvAB6VrCZIUPZJYrNILXcziH6XIdhFI5nAgM4FanXaImigDlx2QxZP0cb2q56ZJbLPf2QCn4zlzoi3BEGwyw8W8PtilsdDb0vr4090n4q3Bav7i9gTMULbiUMK72e+7cgpy2mx0DE6CIHOLDXJtKlD5dVsdO3ZKRZTV6x+IepmNqPpJUD0uUo7Be/6GL3pGlGjpmtgwZUnYLanPsH/J/m3aZmxGxocG+pja2+QYPXmslelZ9RkiMV+Iyfcmm/feeJydFnPPtxe9K1typeRonIMOynlc3O7P4fqYen8RY1c4uCd7hrbC4RmV6mKi5VN/iXHnWVuL1+Wmq0MvRs8CyWtIQJOS3HZT/LJuPmQQcKrPGa7Y/w1jrekx+rl1Ojw2IhNtugcjtJ9gqLLnpfaBxRNIJ4WVDjPyaJ9DSWEd9Qn8JN2F0ixn6A7iCUvyVUPIDrPd6Gu/AQDSAyQ0qx/7242gxjlmcV5o5GPuIORprslNEAt5w/oGHsVvoYVt/eY2ZeUNrFFBShrAM=
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
