---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel.json: REDACTED
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
