apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - cloudflare-tunnel-credentials-sealed.yaml
  - cloudflared-configmap.yaml
  - deployment.yaml
