apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - webtop-credentials-sealed.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - authentik-auth-headers-configmap.yaml
  - authentik-outpost-service.yaml
  - networkpolicy.yaml
  - ingress.yaml
