apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config
  namespace: jumphost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
