---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webtop-credentials
  namespace: jumphost
spec:
  encryptedData:
    password: AgCAZeLOXYovmxTJ5c8K+zT5AMkIz8nwEtsUZPrbc2y9sIIZyUq9C78gyEl4d1vFM668dM96J9+z3DLXSW5fBIxfGpSkg+SEhHO+3PMTXxEiwj3ob/wykyCf13rVko7jzcif3h2Jqhnl3Bb4vwLTRKCJkuZYn3BQSTWRFNleDQrNf2ZtcRUqh4glz0L1KXpW7xnE9rfZaP2QSRjWgGytgvQTV2lYMt8EY02ysKehOMLnnRNKCEkVNxJ6BGugMkbPJzN6vEh2D4TO+i9Bw7+O0hgO6dPglhueMvWpKY8uqKR0mFSef/vyxoQiRztrjpPjK/M4sG+83F5ga6O4YCdbZTsz3yxlu2JTi6H6iSqg3L8Ny1DtOGVKE7rII0Lz4R/OLlNYa0Qg21kImM1iWjdWXLdlw/YC+2fECv+ktsSOIrm5fEdhdSsB4eQzi2WQ1Xf0jMSJkfikpza1YfV0cKpFpoDFPZUgmV7VxuwGud5jl/wXYZVC39Ie0pl+ToGA3HohJNc1nRmUOwvyAeww/3cBuH2gU7WIolJG2C4m4b2Wpk1OxOuIjRIPzaKIlXhtbOlE5YdKPTnpUVEZxad1sIkEPgu/2JlYFvwYGVjnYgTl3Vruq0JJN96/v3VEpopsa5taeTnrNyj0z0EanBeawu+gmyM9Mg54cy3LY9xEK67dc1+nAbDIPXns/4+xrNlDKE0iVAVnHiLK6VeLtOvNjDfsfGEEkkcxd6xRoUg=
    username: AgAbOkO16Lm4oxzbWpsjeSpfZbGeZd9aFIRyvyOUp0x5kqpjNqGC9aDwhnx/51tU+FsT9KNH2iZ/nHwqt+20C82AhnSE7ipk+b5Zx7H6b5qqauGwX+yXp1E7B4pH6P0ALxCmx3mwJHNtCnEL5q81HwUxs2N6saoiEoCbLAw7OTyd3AiAJei4fz+875GXdQi5JL8PEc0W/rJCQvlE6295iG2epuIPBWGj+fkT7lZxEnKpQVpI4pPuqYpToCZhWfPnzDjsN+NpZTiDmt1iBvFYvuPNSvvPySUqcY9w6Hf11YTdEwkX1ylT9IzLBqImzmzU/t9+Kkgk7zh3hnExltBK+Uyqx5bU2I5DupcYDsV2XE8eUZgo8swcqV4MAoZXZfQirZ8P0KMSmunEPyrzgmmDTgJtoaPIgQdkpr9f4CYUQfTal124kmuaLSZa0x1B+WtVuGCwHQHS0KOtSj+Jm8S2JWV4orpaGnOs5JjId9ZmLVIZBUxwZ8W6vAwTMTLFu1clG278ty7SPg5wGL8Vvb83ULcZegevesQfPrZ10w7/S6pNAEKiShwGn2QG8m4pPIUpqqijq3eQVwHIDxfyyU0EwKDpo0qWWojaKDsqEXxM0gWRDn+75HwwHo3wD6qQtsVnQjb10V5ekb93hcQfBQCiXSvz66kd4k/ZbKzenpG/3iZxQWPud6cIg8Bwn+O5BkjUV6B0REFl8A==
  template:
    metadata:
      name: webtop-credentials
      namespace: jumphost
