---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin-credentials
  namespace: forgejo
spec:
  encryptedData:
    email: REDACTED
    password: REDACTED
    username: REDACTED
  template:
    metadata:
      name: forgejo-admin-credentials
      namespace: forgejo
