apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - talos-backup-credentials-sealed.yaml
  - serviceaccount.yaml
  - sealed-secrets-reader-role.yaml
  - sealed-secrets-reader-rolebinding.yaml
  - cronjob.yaml
