---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: talos-backup-credentials
  namespace: cluster-backup
spec:
  encryptedData:
    talosconfig: REDACTED
  template:
    metadata:
      name: talos-backup-credentials
      namespace: cluster-backup
