apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - ippool.yaml
  - l2announcement.yaml
  - authentik-auth-headers-configmap.yaml
  - authentik-outpost-service.yaml
  - ingress.yaml
  - authentik-bypass-api-ingress.yaml
