---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secretKey: REDACTED
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
