---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-credentials
  namespace: authentik
spec:
  encryptedData:
    password: REDACTED
  template:
    metadata:
      name: authentik-postgresql-credentials
      namespace: authentik
