---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAfzE1KwQH2lsPuwsBeh00tkijh6VNcorpNTrLcUPnBCyaO0mZFGdu4MyRWAJYVEp/Hy+fl1UJ3GKK0eW1sLMo5dxKu9TT2sWTyx5b3dnjLHF/kLpgKl5tXn39gYrz9WwBlw3J/ZZxXlWTT5lZbV0s1gwG70hJVPlbl6jE97KO7MHrmRnD9RGgP4xVhk5lhK1rcd6sdx0VrmzGYUpfjRnbPZmlt077W+zVqxyswb+KwbHVOLMKW2vSupATxT1aXQAZZSYeGQ+714kfyZwbY4tEAfw80MCax7IHJ2vAaItUlVdgu3kBrqOpkKaP1FbUKEKE1+LU2v0nXhskOW+Ycq0ZF0ACGycQodccNh7iwpx89KBdUN0RJCRQ5IMFl2ijV2VkQuXCnhWKUy6jH1NyFHMWtYgq5XcVqgOl1osXgVKeU78DbzV0UIU9JeToaBi3H1LIWZY+/mjsnXartdE3MY7SlZbgTc92sb145Dpwp61W7tcuoyRf3Fp8uBDjqCUynHd0Kd/yt7QG6wCRNpBnlNO45PnYllm61kX+LxPjTujrylVGdyj5bVspyRjp2Dj1xhmSbfEKHiUHq5Ksw9XUJGjg/mGMN9f0zvkFbhxSHCLehoH1IUEMObCIt9Oa1pX7a2cAt5DCL2WvX0JlwliNXxPbKnirxzEiTzXL8mDDDPkOY1780Y/BDxVt1IgZjQPPomk64BsiwonlZGmvbFC12dytSWORvY1DIoANRMDQlKZD7x2TDD3JcBiFtOGlLO4zFlyssBdFM7U7wOfX93GmPpVkT
  template:
    metadata:
      name: authentik-postgresql-credentials
      namespace: authentik
