---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secretKey: AgAlypKAxGzI/pVxNgQ0RCTOFX4yggG3EKBveuepGJzx0h0JFINAIUO+MV3V9YIsEcxpWjusVVeDiVh0O6ioyWneWP/7SwWbZ/Dv1k20V7RP/ctJ/L69ayzgyaFDzNUonpnNotw0XvTEh6gM9m+qyIlXlPdJ2p4iLwaVTUuF2THBp5/QNdHLXEI8/mI/cfuo/S8u0oLKyZNUbjyAKlcLLDC4R8FEb61gOZ/qN7qGZf+n74LtzmQkCdfgecCrYjKEbtCMRpkj9+g7TUaobNHFBhNNUR11/KxY9qTo+oqiNimtCXfSrG5Y2VRfoIak8s936vldbklvRPOPRu2v7nYGLBsLhAf8gLafQ2D1c6+nE7lOmGD7PfveoY0HCWxraT0sszs9INyEfkNfXnPnQdGMJmVgSlY1xz8eoyEmK+mfFu6h33wkBEpE+5SJXPtOWHNj05dY2hV8Q0BJE78tIok/vkDNXfBUP6r+U55o2VVPYv2CltHKW2Ix56nvUAI4NdfKww+PL9dgFv6kqncFxRYkk/qdKdMC7OkNpb6lqu55dHcVOFAFXUrfx4uqBIcifDJjop4DuM3ubgu6wrDBc7OcokIKJ7PPddmeow8fzy2f33M7x6Wb6moXFEh9ir88J7Tz79FLNx7d8kC4KL+0zP9BpbdHx2hHnU+SKJjidw5PqcL85HvXh3im0IXj6AYSC3YeJRSnsq9KdCkhGOh/hT7uOY8x5NWziFOLxoL8QoxaeoKuIc6X/enwGcoyYOndtX0N2HfLW4sYoKnE/BawLf9+KpzpP1gD/18NmWZ4NomqcTNswA==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
