apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - authentik-secret-key-sealed.yaml
  - authentik-postgresql-credentials-sealed.yaml
  - authentik-bootstrap-token-sealed.yaml
  - blueprint-sso-configmap.yaml
  - authentik-app-icons-configmap.yaml
  - helmrelease.yaml
  - postgres-mcp-loadbalancer.yaml
