apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - authentik-auth-headers-configmap.yaml
  - authentik-outpost-service.yaml
  - ingress.yaml
  - recurringjob-nightly.yaml
  - recurringjob-trim.yaml
  - servicemonitor.yaml
  - grafana-dashboard-configmap.yaml
  - networkpolicy-allow-prometheus.yaml
