---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCE9vzdTPxS8smD8zj9YSFJEKl2UVy3H6r3zK60GJluq91Y9Ma5+Hx2oSJS+TuUq4lW3V/68oTXndcfOuGDUZ4FeHvia3bxKL/A36j2r5jVosPSezfrD1V1T6r/Va5dZzZcMkuJ0amoMRsMBicKtysBoOQ73U4SQJXemQsdKaSF9/RoK6vVnFMFmJCauNvnt7xubevzBJ3nJpRFVW7TlFcaSLLLK7FAiaZKd0nkAHXMw7/6BzwAXyLe51xRMUpYrrAeuRBcOvCsgNH8uUE/7VMq24sHCw1ORYwn1eoOZv5CUKYm+iG42cUA8zfc8o/KgryXBwlxM5cx48300e7vcULHk13gtHe4w5SuYjbBMRfjqUixMXRyqYXz0TL5t18axUskLSWMayHgwuGBwk6nX36o1C68Th3wq70wFGGiSPmDkHsNF14Zs6hvLisHrAeNpQqeYDt6gEuNJQfeFLmKyd7iazxXkwIx961JazEdQ4f0QkfB3NMAAW67FHZ1KCVxHhlnEGwm/J8kEXecQ2cCxpHdo62ycNH9+AZJ6XhXuN9uKkVLZILZcOuMyP8ZBXrhF5IGNSDHyRKRLniCCaWpJmkYcIeoZZAAWDq8xzA4qn+nSNY3DKVUxLNRzeNC2hCBRimXwr3+9jdwGjiMy4TP9BMuh0UdC3D4N8M4FqnWTatAI6diIEMkMBcejThITPgQ6wqtXRMZ8EiTCBwIe2MClbaDhtGyqkKwvyl32vBzjACdGLPQJwWPdGzrd9jWyyom+Jz1mwbFQg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
