---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: REDACTED
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
