apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - wordpress-credentials-sealed.yaml
  - wordpress-mariadb-credentials-sealed.yaml
  - helmrelease.yaml
  - ingress-www-redirect.yaml
  - grafana-dashboard-configmap.yaml
  - wordpress-security-headers-configmap.yaml
  - mariadb-mcp-loadbalancer.yaml
