apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-security-headers
  namespace: wordpress
data:
  wordpress-htaccess.conf: |
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "geolocation=(), camera=(), microphone=()"
