---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-mariadb-credentials
  namespace: wordpress
spec:
  encryptedData:
    mariadb-metrics-password: REDACTED
    mariadb-password: REDACTED
    mariadb-replication-password: REDACTED
    mariadb-root-password: REDACTED
  template:
    metadata:
      name: wordpress-mariadb-credentials
      namespace: wordpress
