---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-credentials
  namespace: wordpress
spec:
  encryptedData:
    wordpress-password: AgB6cWvL8kSR6+JSINrxQJgczqYGgQToHabkUNX45Tkop1mW45bj5ON+nRDLecAMCI7Q7LyMi4rojHGkeBpqzl/GPc7XvrdPCBTKGRCIv+BwDhGiuJ0zXE7XCH/sM7FA5bpug9g4rAqo1R+frbo7wE240It0u+oVrLxSdmcZUasDl5iJ+jDOEEMuHEdNgIZoHr4BDT1ZsCvNXNLarVudWXvZEEIOS5e1ce3AnrjMYAarnxQFo/P4koMaaggawQfb18xlppCr6Bm3u1U7+ihwqWuRQ2tslRooX3HmjZpE8AOk6adZRfmh3mW/pT6V8vdLC5gCMCbj8sKqcWDsH/hxKJ+5hRUTvYD4QJd7tv2xuJRex0jhoMKDN2iD5R7efq87O6b4sZ9qywtn9dBOtzTsZYdHAo8LtSjbOviaSJGGk83TCLZLwFTCvkDJ0USf0yhU4pxTymc6aUvUc8i+PGNcXHeh4vyMtQ4CrP2zvpDkjGRjUN6W7zkDVaDq6/dgqnZTm4lOhC4D5s2TrCZnGCM+zedJ4oJXtv06i9V9iB8CrxfZRiL12ZYdjzSYFkErPB8NEfEbiBKxcywjk6/aM2iRrfWqn0nbiMeEXBvdCMAFk00Chxw+1mN2GeXdDC3UhJ16JbaKdnfp0IVQI0SzKT2Y3QzNXzylkPkGQ4u2BbP6At7T2zHF+rS4da9NFX25K6bCMpNVM/Gb2TyUV2FzhXkLk57TqYG63JqH3VY=
  template:
    metadata:
      name: wordpress-credentials
      namespace: wordpress
