---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-credentials
  namespace: wordpress
spec:
  encryptedData:
    wordpress-password: REDACTED
  template:
    metadata:
      name: wordpress-credentials
      namespace: wordpress
