---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: REDACTED
  template:
    metadata:
      name: alertmanager-smtp-credentials
      namespace: monitoring
