---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: democratic-csi-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: REDACTED
  template:
    metadata:
      name: democratic-csi-driver-config
      namespace: democratic-csi
