---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryptionKey: AgCELe7eFu1Hjd/ERWNDPdHrxkZOyBp7ow93Prw1/ouJ61snfLoo57cwPkbnKYolYAzWgkHGMFSpQaUapkQKY0hpOMM9LdKo1F5yEbWoDk4Nm4vQmbSBYNmdDr0aBWrKwRbfszcSFExiDLlRCvJef7+alCyuO+N1RXRGxSPXx9Y8h2BYfbzVJdD60tERg61edOCtMuTx6lxq4JzfTkXGzKmla7OWdIVX1lyJyMGw6d52OvSoeER6xy1Um6QmHZf+x9VLmVJwhKc16mgQGAUkUaVxh4vGJdaQ0UstWIuEsMkHqhahSEVh4p4hATus4GbYZFG9/p0lZIAwbTZUyaA0/CgGAO2R0qI78cmH/jTP3J9BPGat8OzAKJyPGuUsgSFsTHZuLmQi3RXGo1L2oFUI5/s6EmLuW91VZ4j4H6WJLXTr1OX7AK/j8aJMbuuvhNEMG2ku422uXW0Em6HV//cvC5Iov4Xi6EJ5c3L0R121Wwqx8kHI6bhxrMtuWBll7DoonMsNtzb1VSMU9oJJeCk97OHniasw7nG1H7s95kQthCpEL/E2DtV6zuSPUiSIh3y0u1IoN2mbqkwA/8EPFj5p6mEcogUDK9BDoe0JAcPz9XFydVXZKJr1V6Kmc1o4idavOOPRRJB2IPsVGEwWv9U7S6eMLmhGxMyAuAxhI5RdEJLPAfb+AppMB1G0BKi+jpiEHXKExQR+05AFlm5UuY9DvccmbeQYVumHV8YYoTpmL+dSktH82dD6+x/ZRK+puL8l3ZBfJdSWO1DxIDFtC6TAtANg
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
