---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    encryptionKey: REDACTED
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
